<?php

declare(strict_types=1);

namespace NetServa\Cms\Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use NetServa\Cms\Models\Category;
use NetServa\Cms\Models\Post;

/**
 * @extends Factory<Post>
 */
class PostFactory extends Factory
{
    protected $model = Post::class;

    public function definition(): array
    {
        $title = fake()->sentence(6);
        $content = fake()->paragraphs(5, true);

        return [
            'title' => $title,
            // Slug will be auto-generated by Sluggable trait
            'excerpt' => fake()->sentence(20),
            'content' => $content,
            'word_count' => str_word_count(strip_tags($content)),
            'is_published' => true,
            'published_at' => fake()->dateTimeBetween('-1 year', 'now'),
            'meta_title' => $title,
            'meta_description' => fake()->sentence(15),
            'meta_keywords' => fake()->words(5, true),
        ];
    }

    public function configure(): static
    {
        return $this->afterCreating(function (Post $post) {
            // Automatically attach a category if none exist
            if ($post->categories()->count() === 0) {
                $category = Category::factory()->post()->create();
                $post->categories()->attach($category);
            }
        });
    }

    public function unpublished(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_published' => false,
            'published_at' => null,
        ]);
    }

    public function published(): static
    {
        return $this->state(fn (array $attributes) => [
            'is_published' => true,
            'published_at' => fake()->dateTimeBetween('-1 year', 'now'),
        ]);
    }

    public function recent(): static
    {
        return $this->state(fn (array $attributes) => [
            'published_at' => fake()->dateTimeBetween('-1 month', 'now'),
        ]);
    }
}
