<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        // SSL Certificate Authorities
        Schema::create('ssl_certificate_authorities', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->enum('ca_type', ['letsencrypt', 'buypass', 'zerossl', 'custom', 'self_signed'])->default('letsencrypt');
            $table->string('acme_directory_url')->nullable();
            $table->boolean('supports_wildcard')->default(true);
            $table->json('auth_config')->nullable();
            $table->text('account_key')->nullable();
            $table->string('account_url')->nullable();
            $table->string('account_email')->nullable();
            $table->text('ca_certificate')->nullable();
            $table->boolean('is_active')->default(true);
            $table->boolean('is_default')->default(false);
            $table->timestamps();

            $table->index(['ca_type', 'is_active']);
        });

        // SSL Certificates
        Schema::create('ssl_certificates', function (Blueprint $table) {
            $table->id();
            $table->string('common_name');
            $table->json('subject_alternative_names')->nullable();
            $table->string('certificate_type')->default('domain');
            $table->foreignId('ssl_certificate_authority_id')->constrained()->cascadeOnDelete();
            $table->text('certificate_pem');
            $table->text('certificate_chain_pem')->nullable();
            $table->text('private_key_pem');
            $table->string('key_type')->default('rsa');
            $table->integer('key_size')->default(2048);
            $table->timestamp('not_valid_before');
            $table->timestamp('not_valid_after');
            $table->boolean('auto_renew')->default(true);
            $table->integer('renew_days_before_expiry')->default(30);
            $table->timestamp('next_renewal_attempt_at')->nullable();
            $table->enum('status', ['pending', 'active', 'expired', 'revoked', 'failed', 'renewing'])->default('pending');
            $table->boolean('is_wildcard')->default(false);
            $table->text('notes')->nullable();
            $table->timestamps();

            $table->unique(['common_name', 'ssl_certificate_authority_id'], 'unique_active_cert_per_domain');
            $table->index(['common_name', 'status']);
            $table->index(['not_valid_after', 'status']);
            $table->index(['auto_renew', 'next_renewal_attempt_at']);
            $table->index(['ssl_certificate_authority_id', 'status']);
            $table->index(['is_wildcard', 'status']);
            $table->index(['status', 'created_at']);
        });

        // SSL Certificate Deployments
        Schema::create('ssl_certificate_deployments', function (Blueprint $table) {
            $table->id();
            $table->foreignId('ssl_certificate_id')->constrained()->cascadeOnDelete();
            $table->unsignedBigInteger('infrastructure_node_id')->nullable();
            $table->string('server_hostname')->nullable();
            $table->string('service_type');
            $table->string('certificate_path');
            $table->string('private_key_path');
            $table->string('certificate_chain_path')->nullable();
            $table->enum('deployment_type', ['new', 'renewal', 'rollback', 'update'])->default('new');
            $table->enum('status', ['pending', 'deploying', 'deployed', 'failed', 'rolled_back'])->default('pending');
            $table->timestamp('deployment_started_at')->nullable();
            $table->timestamp('deployment_completed_at')->nullable();
            $table->json('deployment_config')->nullable();
            $table->text('deployment_errors')->nullable();
            $table->string('deployed_by')->nullable();
            $table->timestamps();

            $table->index(['ssl_certificate_id', 'status']);
            $table->index(['infrastructure_node_id', 'status']);
            $table->index(['service_type', 'status']);
            $table->index(['deployment_completed_at', 'status']);
            $table->index(['deployed_by', 'created_at']);
        });

        // Web Servers
        Schema::create('web_servers', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('hostname');
            $table->text('description')->nullable();
            $table->unsignedBigInteger('infrastructure_node_id');
            $table->enum('server_type', ['nginx', 'apache', 'lighttpd', 'caddy', 'custom'])->default('nginx');
            $table->boolean('is_active')->default(true);
            $table->boolean('is_primary')->default(false);
            $table->string('version')->nullable();
            $table->string('public_ip')->nullable();
            $table->json('listen_addresses')->nullable();
            $table->json('port_config');
            $table->string('server_name')->nullable();
            $table->string('config_path');
            $table->string('sites_path');
            $table->string('enabled_path');
            $table->string('document_root')->default('/var/www');
            $table->string('log_path')->default('/var/log');
            $table->boolean('enable_ssl')->default(true);
            $table->string('ssl_cert_path')->nullable();
            $table->string('ssl_key_path')->nullable();
            $table->json('ssl_protocols')->nullable();
            $table->string('ssl_ciphers')->nullable();
            $table->boolean('ssl_redirect')->default(true);
            $table->boolean('hsts_enabled')->default(true);
            $table->integer('hsts_max_age')->default(31536000);
            $table->integer('worker_processes')->default(4);
            $table->integer('worker_connections')->default(1024);
            $table->integer('keepalive_timeout')->default(65);
            $table->string('client_max_body_size')->default('64M');
            $table->boolean('gzip_enabled')->default(true);
            $table->json('gzip_types')->nullable();
            $table->boolean('server_tokens')->default(false);
            $table->json('security_headers')->nullable();
            $table->boolean('rate_limiting_enabled')->default(true);
            $table->string('rate_limit_zone')->nullable();
            $table->string('rate_limit_rate')->default('10r/s');
            $table->integer('rate_limit_burst')->default(20);
            $table->boolean('php_enabled')->default(true);
            $table->string('default_php_version')->default('8.3');
            $table->json('php_versions')->nullable();
            $table->json('php_modules')->nullable();
            $table->boolean('caching_enabled')->default(true);
            $table->enum('cache_type', ['fastcgi', 'proxy', 'redis', 'memcached'])->default('fastcgi');
            $table->json('cache_config')->nullable();
            $table->string('cache_path')->nullable();
            $table->string('cache_zone_size')->default('10m');
            $table->boolean('load_balancing_enabled')->default(false);
            $table->enum('lb_method', ['round_robin', 'least_conn', 'ip_hash', 'least_time', 'random'])->default('round_robin');
            $table->boolean('health_checks_enabled')->default(true);
            $table->integer('health_check_interval')->default(30);
            $table->integer('fail_timeout')->default(30);
            $table->integer('max_fails')->default(3);
            $table->boolean('access_log_enabled')->default(true);
            $table->string('access_log_format')->default('combined');
            $table->string('access_log_path')->nullable();
            $table->boolean('error_log_enabled')->default(true);
            $table->string('error_log_level')->default('error');
            $table->string('error_log_path')->nullable();
            $table->integer('log_retention_days')->default(30);
            $table->integer('total_virtual_hosts')->default(0);
            $table->integer('active_virtual_hosts')->default(0);
            $table->unsignedBigInteger('total_requests_today')->default(0);
            $table->unsignedBigInteger('bandwidth_used_today')->default(0);
            $table->decimal('average_response_time_ms', 10, 2)->nullable();
            $table->integer('current_connections')->default(0);
            $table->decimal('cpu_usage_percent', 5, 2)->default(0);
            $table->decimal('memory_usage_percent', 5, 2)->default(0);
            $table->enum('service_status', ['running', 'stopped', 'failed', 'reloading', 'unknown'])->default('unknown');
            $table->timestamp('last_restart_at')->nullable();
            $table->timestamp('last_config_reload_at')->nullable();
            $table->text('last_error')->nullable();
            $table->integer('restart_count')->default(0);
            $table->text('main_config')->nullable();
            $table->json('modules_enabled')->nullable();
            $table->text('custom_directives')->nullable();
            $table->timestamp('config_last_modified')->nullable();
            $table->string('config_checksum')->nullable();
            $table->boolean('backup_enabled')->default(true);
            $table->string('backup_schedule')->default('0 2 * * *');
            $table->integer('backup_retention_days')->default(30);
            $table->timestamp('last_backup_at')->nullable();
            $table->unsignedBigInteger('last_backup_size_bytes')->nullable();
            $table->enum('health_status', ['healthy', 'warning', 'error', 'maintenance', 'unknown'])->default('unknown');
            $table->text('health_message')->nullable();
            $table->timestamp('last_health_check_at')->nullable();
            $table->json('health_checks')->nullable();
            $table->integer('uptime_percentage')->default(100);
            $table->boolean('maintenance_mode')->default(false);
            $table->text('maintenance_message')->nullable();
            $table->timestamp('maintenance_started_at')->nullable();
            $table->timestamp('maintenance_ends_at')->nullable();
            $table->timestamp('last_update')->nullable();
            $table->string('update_available')->nullable();
            $table->json('webhook_endpoints')->nullable();
            $table->json('monitoring_endpoints')->nullable();
            $table->boolean('auto_ssl_enabled')->default(false);
            $table->string('ssl_provider')->nullable();
            $table->json('ssl_config')->nullable();
            $table->json('custom_config')->nullable();
            $table->json('environment_variables')->nullable();
            $table->text('nginx_conf')->nullable();
            $table->text('apache_conf')->nullable();
            $table->json('tags')->nullable();
            $table->json('metadata')->nullable();
            $table->string('created_by')->nullable();
            $table->string('updated_by')->nullable();
            $table->timestamps();

            $table->unique(['hostname', 'infrastructure_node_id']);
            $table->index(['is_active', 'server_type']);
            $table->index(['infrastructure_node_id', 'is_active']);
            $table->index(['hostname', 'is_active']);
            $table->index(['service_status', 'last_health_check_at']);
            $table->index(['health_status', 'last_health_check_at']);
            $table->index(['maintenance_mode', 'maintenance_ends_at']);
            $table->index(['is_primary', 'server_type']);
            $table->index('created_at');
        });

        // Virtual Hosts
        Schema::create('virtual_hosts', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->json('server_names');
            $table->string('primary_domain');
            $table->text('description')->nullable();
            $table->foreignId('web_server_id')->constrained('web_servers')->cascadeOnDelete();
            $table->unsignedBigInteger('infrastructure_node_id')->nullable();
            $table->boolean('is_active')->default(true);
            $table->boolean('is_default')->default(false);
            $table->string('document_root');
            $table->string('index_files')->default('index.php index.html index.htm');
            $table->boolean('http_enabled')->default(true);
            $table->integer('http_port')->default(80);
            $table->boolean('https_enabled')->default(true);
            $table->integer('https_port')->default(443);
            $table->boolean('force_https')->default(true);
            $table->boolean('ssl_enabled')->default(true);
            $table->string('ssl_certificate_path')->nullable();
            $table->string('ssl_private_key_path')->nullable();
            $table->timestamp('ssl_expires_at')->nullable();
            $table->boolean('php_enabled')->default(true);
            $table->string('php_version')->default('8.4');
            $table->text('custom_nginx_config')->nullable();
            $table->text('custom_apache_config')->nullable();
            $table->timestamps();

            $table->unique(['primary_domain', 'web_server_id']);
            $table->index(['web_server_id', 'is_active']);
            $table->index(['primary_domain', 'is_active']);
        });

        // Web Applications
        Schema::create('web_applications', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('slug');
            $table->text('description')->nullable();
            $table->unsignedBigInteger('virtual_host_id')->nullable();
            $table->enum('application_type', ['wordpress', 'laravel', 'symfony', 'drupal', 'joomla', 'magento', 'nodejs', 'react', 'vue', 'angular', 'nextjs', 'nuxtjs', 'static', 'custom'])->default('static');
            $table->string('framework_version')->nullable();
            $table->json('requirements')->nullable();
            $table->enum('installation_method', ['manual', 'auto', 'git', 'composer', 'npm'])->default('manual');
            $table->string('repository_url')->nullable();
            $table->string('repository_branch')->default('main');
            $table->json('repository_credentials')->nullable();
            $table->string('installation_path');
            $table->enum('installation_status', ['pending', 'installing', 'installed', 'failed', 'updating'])->default('pending');
            $table->timestamp('installed_at')->nullable();
            $table->text('installation_log')->nullable();
            $table->string('current_version')->nullable();
            $table->string('available_version')->nullable();
            $table->boolean('auto_update_enabled')->default(false);
            $table->enum('update_channel', ['stable', 'beta', 'nightly'])->default('stable');
            $table->timestamp('last_update_check')->nullable();
            $table->timestamp('last_updated_at')->nullable();
            $table->json('update_history')->nullable();
            $table->json('configuration')->nullable();
            $table->json('environment_variables')->nullable();
            $table->json('config_files')->nullable();
            $table->boolean('config_managed')->default(true);
            $table->string('config_template')->nullable();
            $table->timestamp('config_last_updated')->nullable();
            $table->boolean('database_required')->default(false);
            $table->enum('database_type', ['mysql', 'postgresql', 'sqlite', 'mongodb'])->nullable();
            $table->string('database_host')->nullable();
            $table->integer('database_port')->nullable();
            $table->string('database_name')->nullable();
            $table->string('database_user')->nullable();
            $table->string('database_password')->nullable();
            $table->json('database_config')->nullable();
            $table->boolean('database_migrations_enabled')->default(true);
            $table->string('php_version')->nullable();
            $table->json('php_extensions')->nullable();
            $table->json('php_settings')->nullable();
            $table->string('composer_version')->nullable();
            $table->boolean('composer_install_dev')->default(false);
            $table->string('nodejs_version')->nullable();
            $table->string('npm_version')->nullable();
            $table->json('npm_scripts')->nullable();
            $table->string('process_manager')->nullable();
            $table->json('process_config')->nullable();
            $table->boolean('build_required')->default(false);
            $table->string('build_command')->nullable();
            $table->string('build_directory')->nullable();
            $table->json('build_artifacts')->nullable();
            $table->enum('build_status', ['pending', 'building', 'success', 'failed'])->default('pending');
            $table->timestamp('last_build_at')->nullable();
            $table->text('build_log')->nullable();
            $table->boolean('asset_compilation')->default(false);
            $table->string('asset_compiler')->nullable();
            $table->json('asset_config')->nullable();
            $table->boolean('minification_enabled')->default(true);
            $table->boolean('css_preprocessing')->default(false);
            $table->string('css_preprocessor')->nullable();
            $table->boolean('caching_enabled')->default(true);
            $table->json('cache_config')->nullable();
            $table->boolean('compression_enabled')->default(true);
            $table->boolean('cdn_enabled')->default(false);
            $table->json('cdn_config')->nullable();
            $table->boolean('lazy_loading_enabled')->default(false);
            $table->boolean('security_headers_enabled')->default(true);
            $table->json('security_config')->nullable();
            $table->boolean('csrf_protection')->default(true);
            $table->boolean('xss_protection')->default(true);
            $table->boolean('sql_injection_protection')->default(true);
            $table->json('security_rules')->nullable();
            $table->boolean('backup_enabled')->default(true);
            $table->string('backup_schedule')->default('0 4 * * *');
            $table->integer('backup_retention_days')->default(14);
            $table->boolean('backup_database')->default(true);
            $table->boolean('backup_files')->default(true);
            $table->json('backup_excludes')->nullable();
            $table->timestamp('last_backup_at')->nullable();
            $table->boolean('monitoring_enabled')->default(true);
            $table->json('monitoring_config')->nullable();
            $table->boolean('error_tracking_enabled')->default(true);
            $table->string('error_tracking_service')->nullable();
            $table->json('logging_config')->nullable();
            $table->string('log_level')->default('error');
            $table->decimal('average_response_time', 10, 2)->nullable();
            $table->decimal('average_memory_usage', 10, 2)->nullable();
            $table->decimal('average_cpu_usage', 5, 2)->nullable();
            $table->unsignedBigInteger('daily_requests')->default(0);
            $table->unsignedBigInteger('monthly_requests')->default(0);
            $table->unsignedBigInteger('storage_used_bytes')->default(0);
            $table->enum('health_status', ['healthy', 'warning', 'error', 'maintenance'])->default('healthy');
            $table->text('health_message')->nullable();
            $table->timestamp('last_health_check')->nullable();
            $table->json('health_checks')->nullable();
            $table->boolean('is_responding')->default(true);
            $table->integer('uptime_percentage')->default(100);
            $table->json('wordpress_config')->nullable();
            $table->json('laravel_config')->nullable();
            $table->json('nodejs_config')->nullable();
            $table->json('static_config')->nullable();
            $table->json('pre_deployment_hooks')->nullable();
            $table->json('post_deployment_hooks')->nullable();
            $table->json('rollback_hooks')->nullable();
            $table->boolean('zero_downtime_deployment')->default(false);
            $table->integer('deployment_timeout')->default(300);
            $table->boolean('testing_enabled')->default(false);
            $table->string('test_command')->nullable();
            $table->enum('test_framework', ['phpunit', 'jest', 'mocha', 'cypress', 'custom'])->nullable();
            $table->json('test_config')->nullable();
            $table->timestamp('last_test_run')->nullable();
            $table->enum('last_test_result', ['passed', 'failed', 'pending'])->nullable();
            $table->boolean('staging_enabled')->default(false);
            $table->string('staging_url')->nullable();
            $table->json('environment_config')->nullable();
            $table->enum('current_environment', ['development', 'staging', 'production'])->default('production');
            $table->string('license')->nullable();
            $table->json('compliance_requirements')->nullable();
            $table->boolean('gdpr_compliant')->default(false);
            $table->json('privacy_config')->nullable();
            $table->timestamp('license_expires_at')->nullable();
            $table->json('plugins_installed')->nullable();
            $table->json('modules_enabled')->nullable();
            $table->json('themes_available')->nullable();
            $table->string('active_theme')->nullable();
            $table->boolean('plugin_auto_updates')->default(false);
            $table->boolean('api_enabled')->default(false);
            $table->string('api_version')->nullable();
            $table->json('api_config')->nullable();
            $table->json('webhooks')->nullable();
            $table->json('external_integrations')->nullable();
            $table->json('api_keys')->nullable();
            $table->boolean('maintenance_mode')->default(false);
            $table->text('maintenance_message')->nullable();
            $table->timestamp('maintenance_start')->nullable();
            $table->timestamp('maintenance_end')->nullable();
            $table->boolean('scheduled_maintenance')->default(false);
            $table->string('maintenance_window')->nullable();
            $table->json('tags')->nullable();
            $table->json('metadata')->nullable();
            $table->string('owner')->nullable();
            $table->string('developer')->nullable();
            $table->string('maintainer')->nullable();
            $table->text('notes')->nullable();
            $table->string('created_by')->nullable();
            $table->string('updated_by')->nullable();
            $table->timestamps();

            $table->unique(['slug', 'virtual_host_id']);
            $table->index(['virtual_host_id', 'application_type']);
            $table->index(['slug', 'virtual_host_id']);
            $table->index(['installation_status', 'installed_at']);
            $table->index(['health_status', 'last_health_check']);
            $table->index(['auto_update_enabled', 'last_update_check']);
            $table->index(['backup_enabled', 'last_backup_at']);
            $table->index(['maintenance_mode', 'maintenance_end']);
            $table->index(['owner', 'application_type']);
            $table->index(['current_environment', 'health_status']);
            $table->index('created_at');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('web_applications');
        Schema::dropIfExists('virtual_hosts');
        Schema::dropIfExists('web_servers');
        Schema::dropIfExists('ssl_certificate_deployments');
        Schema::dropIfExists('ssl_certificates');
        Schema::dropIfExists('ssl_certificate_authorities');
    }
};
